app4:
  container_name: sonarqube4
  image: sonarqube:4.5.7
  links:
    - db
  volumes:
    - sonarqube_app4_data:/opt/sonarqube/data
    - sonarqube_app4_ext:/opt/sonarqube/extensions
  ports:
    - "19000:9000"
  environment:
    SONARQUBE_JDBC_USERNAME: sonar
    SONARQUBE_JDBC_PASSWORD: "7ujmNHY&%TGB"
    SONARQUBE_JDBC_URL: jdbc:postgresql://db/sonar4

app5:
  container_name: sonarqube5
  image: sonarqube:5.6
  links:
    - db
  volumes:
    - sonarqube_app5_data:/opt/sonarqube/data
    - sonarqube_app5_ext:/opt/sonarqube/extensions
  ports:
    - "29000:9000"
  environment:
    SONARQUBE_JDBC_USERNAME: sonar
    SONARQUBE_JDBC_PASSWORD: "7ujmNHY&%TGB"
    SONARQUBE_JDBC_URL: jdbc:postgresql://db/sonar5

db:
  container_name: sonarqube_db
  build: ./sonarqube-db
  volumes:
    - sonarqube_db_data:/var/lib/postgresql/data
  ports:
    - "5432:5432"
